### ISSUE TITLE
Bulk create transactions fails with bad_request detail={"transactions":["This field is required."]}

### ISSUE THREAD

**Issue by askielboe** [brunomvsouza/ynab.go#5]
First of all, thanks a lot for creating this package! It's a good change for me to save some money using 
YNAB while learning the golang at the same time. :) So on to my problem:

I'm trying to use ynab.go to add transactions to my YNAB account. I'm currently stuck with this error when I try to `client.Transaction().BulkCreateTransactions()`

    api: error id=400 name=bad_request detail={"transactions":["This field is required."]}

I'm not really sure how to best debug this issue. I've tried copying the code from `TestService_BulkCreateTransactions()`, filling out my account and budget IDs, but I still get the same error.

Inspecting the payload that ynab.go creates in `BulkCreateTransactions` it seems that everything looks fine (I've masked my account id):

```json
{
  "transactions": [
    {
      "account_id": "MY-ACCOUNT-ID",
      "date": "2018-11-13",
      "amount": -9000,
      "cleared": "cleared",
      "approved": true,
      "payee_id": "0d0e928d-312a-4bcd-89c4-e02f40d1fe46",
      "payee_name": "bla bla bla",
      "category_id": "f3cc4f55-312a-4bcd-89c4-db34379cb1dc",
      "memo": "nice memo",
      "flag_color": "blue",
      "import_id": "asdfg"
    },
    {
      "account_id": "MY-ACCOUNT-ID",
      "date": "2018-11-13",
      "amount": -9000,
      "cleared": "cleared",
      "approved": true,
      "payee_id": "0d0e928d-312a-4bcd-89c4-e02f40d1fe46",
      "payee_name": "bla bla bla",
      "category_id": "f3cc4f55-312a-4bcd-89c4-db34379cb1dc",
      "memo": "nice memo",
      "flag_color": "blue",
      "import_id": "asdfg"
    }
  ]
}
```

Not quite sure where to go from here? It sure looks like the `transactions` field is included in the payload. So maybe the actual error is something else?

**Comment by brunomvsouza** [comment]
Thanks again for the through report @askielboe! It helped to find the issue quickly.

Interesting idea of saving money and learning Go at the same time. I wish you succeed! 
If you find any other issue, please be my guest.

Cheers!

**Comment by askielboe** [comment]
Excellent! Thanks for the quick fix and the encouragement! 👍
